# Custom Language File for Launcher Customizer

[ejs.app]
title = "Nation Quest Launcher"

[ejs.landing]
mediaGitHubURL = "https://nationquest.websr.fr/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/p6JyeZXkRa"

[ejs.settings]
sourceGithubLink = "https://nationquest.websr.fr/"
supportLink = "https://discord.gg/p6JyeZXkRa"

[ejs.welcome]
welcomeHeader = "WELCOME TO NATION QUEST"
welcomeDescription = "Salut jeune aventurier ! Ici, c’est Nation Quest. Viens sur Artemis ou Cresus et crée ta légende ! Améliore tes compétences et ton équipement, et pars combattre les plus grands boss ! Bonne Route."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics d'Artemis."
